### ISSUE TITLE
Refactoring Data Types (Draft) 

### ISSUE THREAD

**Issue by swagle8987** [sriram98v/phylo-rs#10]
Just trying to refactor to scratch an itch because I think the node type can be simplified

For now the current proposal I have has the following changes

- Consolidate NodeType and NodeID into a node struct :: Essentially we combine them into a node struct that has nodeid, is_leaf as a boolean and label as a taxa. We are handling these cases anyways for nodes in the tree structure so this is more cosmetic rather than performance based. To avoid performance hits with all the other hashmaps, the struct will hash by its id and is equivalent to its id. This ties into the point below
- Use usize instead of NodeID :: For all the functions that use &NodeID(which effectively translates to a pointer to a usize integer) we could instead just keep the usize type directly since it has move semantics avoiding another area where the users might have to grapple with the borrow checker. 
- Children is now HashMap<usize, HashMap<usize,Option<EdgeWeight>> :: Simply because you cannot have two edge weights to the exact same node. Enforcing it as a HashMap also allows for faster updates. 

P.S. - Is rustfmt a part of automatic actions? We might want to add that as either an automatic action or simply as best practice. 

Let me know if all these make sense.

**Comment by sriram98v** [comment]
Yep, this can be done. I have pushed some changes to this branch with new implementations of the rooted tree and rooted node trait. Some of the method implementations for each are pending, and more can be added. It also might be a good idea to move methods like SPR, NNI etc to tree instead of PhyloTree as these are not specific to phylogenetic trees....

**Comment by swagle8987** [comment]
For future reference 

NodeID : Hash + Clone + Drop

Node { 
- getid(&self) -> NodeID 
- setid (&mut self, NodeID)
- addchild(&mut self, Node)
- setparent(&mut self,Node)
- getparent(&mut self, Node);
- getchildren(&mut self) -> impl Iterator<NodeID>
- isleaf(&self) -> boolean
- removechild(&mut self, NodeID)
}

**Comment by sriram98v** [comment]
I have updated the trait bounds for nodeid on the node trait.
