### ISSUE TITLE
create rooted phylo tree struct and impl generic rooted tree traits

### ISSUE THREAD

**Issue by sriram98v** [sriram98v/phylo-rs#2]

**Comment by sriram98v** [comment]
Add_child needs to be implemented, which should panic if the node is identical to an existing node. Identical means children, parent and taxa are the same.

**Comment by sriram98v** [comment]
The clean method also appears to be incorrectly implemented and needs to be replace. It is essentially a method that mutates self and removes half nodes (nodes with only one child).

Another method to add is a balance_tree.

**Comment by swagle8987** [comment]
I had a question regarding simplertree.rs

Wouldn't it be simpler if we just defined the bare-bones version of what we think a tree should be?
i.e. we don't restrict or assume responsibility for node structs or edges just that each tree must have some idea of a node, some idea of an edge and related methods to those
For example:
```
pub trait SimpleTree{
    type Node = Hash + Debug + PartialEq
    type Edge = Debug + PartialEq
    type EdgeWeight
    fn add_node(&mut self) -> Node;
    fn add_edge(&mut self, node1:Node, node2:Node, distance:Option<EdgeWeight>) -> Edge
    fn remove_node(&mut self, node:Node) -> Node
    fn remove_edge(&mut self,edge:Edge) -> Edge
    fn set_edge_weight(&mut self, edge:Edge, distance:Option<EdgeWeight>);
}
```
Even better imo would be to make the simple tree trait bound explicit
```
pub trait SimpleTree<Node,Edge,EdgeWeight> where
Node : Hash+Debug+PartialEq
Edge : Debug+PartialEq
EdgeWeight : Debug{
    fn add_node(&mut self) -> Node;
    fn add_edge(&mut self, node1:Node, node2:Node, distance:Option<EdgeWeight>) -> Edge
    fn remove_node(&mut self, node:Node) -> Node
    fn remove_edge(&mut self,edge:Edge) -> Edge
    fn set_edge_weight(&mut self, edge:Edge, distance:Option<EdgeWeight>);
}
```
SimpleRTree would then inherit from SimpleTree and simply be concerned with defining the required methods for rooted tree traits. The aim would be to cut methods that are not always necessary for a tree like spr and nni. These can then be defined as methods of a struct and the scope of these is up to the implementation of those structs i.e. if someone wants just a barebones tree struct that simply iterates over the nodes in a tree-like manner, they do not need to implement graft or prune or any of the other methods.

**Comment by sriram98v** [comment]
Normally, that would make sense. I am currently refactoring the simpletree and node modules in another branch, where there will exist a default implementation for more advanced methods. That would resolve the issue of using a tree-struct with barebone methods. 

I would also like to add that if the use case is simply basic tree iterations, why not use the struct that is also provided?
