### ISSUE TITLE
Crate hygiene considerations

### ISSUE THREAD

**Issue by sammysheep** [sriram98v/phylo-rs#22]
I noticed a few things that could benefit this repo, but feel free to take it or leave it.

- Run `clippy` on your code. I did. There were numerous good suggestions that simplify the structure and logic without changing the heart of what you've written. Sometimes you have to add changes iteratively to get the most benefit. Let me know if you'd like a PR.
- Run `rustfmt` on your code to ensure consistent style. I run it on "save" myself.
- Put dependencies like Rayon behind _features_. Indeed, consider composing your library into multiple features to let users pick and choose what they want to depend on before dividing into sub-crates (for example, your default data structure could be behind a feature instead of a separate crate). You can always make the default features the same as what you have now so there will be no breakage downstream.
- For error-handling, consider when an `Option` will do and if not, see if you can eschew `Anyhow`. Most people use `Anyhow` in application crates rather than library ones, but to each their own.

Let me know if you are interested in a PR for any of this. It was nice chatting with you last week!

**Comment by sammysheep** [comment]
I could provide some example features but it depends on what you want going forward. 

In any case, I'll wait until you've done your formatting and linting to avoid a more complicated merge.

**Comment by sriram98v** [comment]
Yep, both linting and formatting should be fixed now.
