### ISSUE TITLE
Breaking changes introduced in patch update

### ISSUE THREAD

**Issue by Cydhra** [sriram98v/phylo-rs#26]
Between 0.3.1 and 0.3.4 the `get_node` function of trees changed its return type from `Result` to `Option` breaking code that relies on semantic versioning (i.e. specifies `0.3(.X)` as the library version which Cargo will happily switch from `0.3.1` to `0.3.4` because versions before `1.0` are expected to keep breaking changes between minor version increments).

**Comment by sriram98v** [comment]
Yes, I understand. I apologize for the issues; this crate is under active development, and many more changes can be expected in the next month. I plan on pushing ```1.0``` before the end of the year, after which method signatures are not expected to change so drastically.

**Comment by Cydhra** [comment]
Yeah no problem, just remember to increase the minor version (i.e. 1.3.1 -> 1.4.0) when making breaking changes.

**Comment by sriram98v** [comment]
Understood. Thank you, this has been a valuable learning experience!
